title: Kids Hack Day
email: murilo@kidshackday.com
description: Kids Hack Day website
baseurl: "/kidshackday.org" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kidshackday
github_username:  kidshackday

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
